version: "3.9"
services:
    db:
      image: mysql:5.7
      restart: always
      container_name: TaxDeductSystem_DB_MySQL
      ports:
        - 3308:3306
      environment: 
        MYSQL_DATABASE: taxdeduct
        MYSQL_USER: root
        MYSQL_PASSWORD: 1234
        MYSQL_ROOT_PASSWORD: 1234
      volumes:
        - mysql-data:/var/lib/mysql
        
    web:
      build: .
      ports:
        - "80:8000"
      container_name: TaxDeductSystem_Back_Web
      volumes:
        - "./BackTaxDeductSystem:/BackTaxDeductSystem"
      command: python manage.py runserver 0.0.0.0:8000
      depends_on:
        - db
      environment:
        MYSQL_HOST: db
      env_file:
        - .env.prod

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      depends_on:
        - db
      ports:
        - 8001:80
      environment:
        PMA_PASSWORD: 1234
        PMA_USER: root
        PMA_HOSTS: db

volumes:
  mysql-data: