version: "3.9"
services:
    db:
      image: mysql:5.7
      restart: always
      ports:
        - 3308:3306
      environment: 
        MYSQL_DATABASE: taxdeduct
        MYSQL_USER: root
        MYSQL_PASSWORD: 1234
        MYSQL_ROOT_PASSWORD: 1234
      volumes:
        - mysql-data:/var/lib/mysql
        
    web:
      build: .
      ports:
        - "8000:8000"
      volumes:
        - "./BackTaxDeductSystem:/BackTaxDeductSystem"
      command: python manage.py runserver 0.0.0.0:8000
      depends_on:
        - db
      environment:
        MYSQL_HOST: db

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      restart: always
      depends_on:
        - db
      ports:
        - 8001:80
      environment:
        PMA_PASSWORD: 1234
        PMA_USER: root
        PMA_HOSTS: db

volumes:
  mysql-data: